/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_sysml_runtime_matrix_data_LibMatrixNative */

#ifndef _Included_org_apache_sysml_runtime_matrix_data_LibMatrixNative
#define _Included_org_apache_sysml_runtime_matrix_data_LibMatrixNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_sysml_runtime_matrix_data_LibMatrixNative
 * Method:    matrixMultDenseDense
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_org_apache_sysml_runtime_matrix_data_LibMatrixNative_matrixMultDenseDense
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     org_apache_sysml_runtime_matrix_data_LibMatrixNative
 * Method:    conv2dDense
 * Signature: ([D[D[DIIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_apache_sysml_runtime_matrix_data_LibMatrixNative_conv2dDense
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_apache_sysml_runtime_matrix_data_LibMatrixNative
 * Method:    conv2dBackwardFilterDense
 * Signature: ([D[D[DIIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_apache_sysml_runtime_matrix_data_LibMatrixNative_conv2dBackwardFilterDense
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
